/// OctoIcon glyph 名字：与前端 sprite 的 `<symbol id>` 一一对应。
/// 独立成文件（不依赖 SwiftUI），让服务层（如 HistoryStore 的行按钮）和
/// 自检可执行文件都能引用，避免拼写漂移。
enum OctoIconName {
    static let addImages = "icon-add-images"
    static let back = "icon-back"
    static let check = "icon-check"
    static let chevronDown = "icon-chevron-down"
    static let chevronLeft = "icon-chevron-left"
    static let chevronRight = "icon-chevron-right"
    static let close = "icon-close"
    static let compare = "icon-compare"
    static let compress = "icon-compress"
    static let copy = "icon-copy"
    static let error = "icon-error"
    static let export = "icon-export"
    static let finder = "icon-finder"
    static let folderAdd = "icon-folder-add"
    static let folderOpen = "icon-folder-open"
    static let history = "icon-history"
    static let info = "icon-info"
    static let minus = "icon-minus"
    static let moon = "icon-moon"
    static let pause = "icon-pause"
    static let play = "icon-play"
    static let queue = "icon-queue"
    static let recompress = "icon-recompress"
    static let resetView = "icon-reset-view"
    static let restore = "icon-restore"
    static let results = "icon-results"
    static let save = "icon-save"
    static let settings = "icon-settings"
    static let sliders = "icon-sliders"
    static let sortAsc = "icon-sort-asc"
    static let sortDesc = "icon-sort-desc"
    static let splitGrip = "icon-split-grip"
    static let stop = "icon-stop"
    static let sun = "icon-sun"
    static let themeAuto = "icon-theme-auto"
    static let trash = "icon-trash"
    static let warning = "icon-warning"
    static let zoomIn = "icon-zoom-in"
    static let zoomOut = "icon-zoom-out"
}
